name: jumsRebootFlutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  firebase_messaging: ^7.0.3
  firebase_core: "0.5.3"
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.11.0
  http: ^0.12.2
  in_app_update: ^1.1.15
  package_info: ^0.4.3+2
  path_provider: ^1.6.27
  share: ^0.6.5+4
  share_extend: ^1.1.9
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  syncfusion_flutter_pdfviewer: ^18.4.49-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
flutter_native_splash:
  image: assets/logo_trans.png
  color: "#ffffff"
